# Generated by Django 5.1 on 2026-04-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencies', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('desired_salary_min', models.IntegerField(blank=True, null=True)),
                ('desired_salary_max', models.IntegerField(blank=True, null=True)),
                ('preferred_contract_type', models.CharField(choices=[('pj', 'PJ'), ('clt', 'CLT'), ('both', 'Both')], default='both', max_length=20)),
                ('preferred_work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('any', 'Any')], default='any', max_length=20)),
                ('preferred_roles', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
