# Generated by Django 5.1 on 2026-04-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('contract_type', models.CharField(choices=[('pj', 'PJ'), ('clt', 'CLT'), ('both', 'Both'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('nerdin', 'Nerdin'), ('geekhunter', 'GeekhHunter')], max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('score_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-score', '-scraped_at'],
                'unique_together': {('external_id', 'source')},
            },
        ),
    ]
