# Generated by Django 5.1 on 2026-05-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [models.OrderBy(models.F('score'), descending=True, nulls_last=True), '-scraped_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
