# Generated by Django 5.1 on 2026-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_replace_applied_with_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('nerdin', 'Nerdin'), ('geekhunter', 'GeekhHunter'), ('indeed', 'Indeed')], max_length=20),
        ),
    ]
